// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xktjbjkgubknxjvjltif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdGpiamtndWJrbnhqdmpsdGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Nzc3NjQsImV4cCI6MjA2MTQ1Mzc2NH0.nDeiq0R77n2VqiusZY0er3-Lx6VnA9g8Qmpiycka6oU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);